module.exports = {
    /**
    * An email template (HTML) for transfer.
    *
    * @param    JSON     data
    * @return   string
    */
    transferHTML : function(data)
    {
        var code = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n';
        code += '<html xmlns="http://www.w3.org/1999/xhtml">\n';
        code += '<head>\n';
        code += '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n';
        code += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
        code += '<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n';
        code += '<meta name="format-detection" content="telephone=no" />\n';
        code += '<title>E-Mail</title>\n';
        code += '<style type="text/css">html{background-color:#e1e1e1;margin:0;padding:0}body,#bodyTable,#bodyCell,#bodyCell{height:100%!important;margin:0;padding:0;width:100%!important;font-family:Helvetica,Arial,"Lucida Grande",sans-serif}table{border-collapse:collapse}table[id=bodyTable]{width:100%!important;margin:auto;max-width:500px!important;color:#7a7a7a;font-weight:normal}img,a img{border:0;outline:0;text-decoration:none;height:auto;line-height:100%}a{text-decoration:none!important;border-bottom:1px solid}h1,h2,h3,h4,h5,h6{color:#5f5f5f;font-weight:normal;font-family:Helvetica;font-size:20px;line-height:125%;text-align:Left;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;padding-top:0;padding-bottom:0;padding-left:0;padding-right:0}.ReadMsgBody{width:100%}.ExternalClass{width:100%}.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{line-height:100%}table,td{mso-table-lspace:0;mso-table-rspace:0}#outlook a{padding:0}img{-ms-interpolation-mode:bicubic;display:block;outline:0;text-decoration:none}body,table,td,p,a,li,blockquote{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-weight:normal!important}.ExternalClass td[class="ecxflexibleContainerBox"] h3{padding-top:10px!important}h1{display:block;font-size:26px;font-style:normal;font-weight:normal;line-height:100%}h2{display:block;font-size:20px;font-style:normal;font-weight:normal;line-height:120%}h3{display:block;font-size:17px;font-style:normal;font-weight:normal;line-height:110%}h4{display:block;font-size:18px;font-style:italic;font-weight:normal;line-height:100%}.flexibleImage{height:auto}.linkRemoveBorder{border-bottom:0!important}table[class=flexibleContainerCellDivider]{padding-bottom:0!important;padding-top:0!important}body,#bodyTable{background-color:#e1e1e1}#emailHeader{background-color:#e1e1e1}#emailBody{background-color:#fff}#emailFooter{background-color:#e1e1e1}.nestedContainer{background-color:#f8f8f8;border:1px solid #ccc}.emailButton{background-color:#205478;border-collapse:separate}.buttonContent{color:#fff;font-family:Helvetica;font-size:18px;font-weight:bold;line-height:100%;padding:15px;text-align:center}.buttonContent a{color:#fff;display:block;text-decoration:none!important;border:0!important}.emailCalendar{background-color:#fff;border:1px solid #ccc}.emailCalendarMonth{background-color:#205478;color:#fff;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:bold;padding-top:10px;padding-bottom:10px;text-align:center}.emailCalendarDay{color:#205478;font-family:Helvetica,Arial,sans-serif;font-size:60px;font-weight:bold;line-height:100%;padding-top:20px;padding-bottom:20px;text-align:center}.imageContentText{margin-top:10px;line-height:0}.imageContentText a{line-height:0}#invisibleIntroduction{display:none!important}span[class=ios-color-hack] a{color:#275100!important;text-decoration:none!important}span[class=ios-color-hack2] a{color:#205478!important;text-decoration:none!important}span[class=ios-color-hack3] a{color:#8B8B8B!important;text-decoration:none!important}.a[href^="tel"],a[href^="sms"]{text-decoration:none!important;color:#606060!important;pointer-events:none!important;cursor:default!important}.mobile_link a[href^="tel"],.mobile_link a[href^="sms"]{text-decoration:none!important;color:#606060!important;pointer-events:auto!important;cursor:default!important}@media only screen and (max-width:480px){body{width:100%!important;min-width:100%!important}table[id="emailHeader"],table[id="emailBody"],table[id="emailFooter"],table[class="flexibleContainer"],td[class="flexibleContainerCell"]{width:100%!important}td[class="flexibleContainerBox"],td[class="flexibleContainerBox"] table{display:block;width:100%;text-align:left}td[class="imageContent"] img{height:auto!important;width:100%!important;max-width:100%!important}img[class="flexibleImage"]{height:auto!important;width:100%!important;max-width:100%!important}img[class="flexibleImageSmall"]{height:auto!important;width:auto!important}table[class="flexibleContainerBoxNext"]{padding-top:10px!important}table[class="emailButton"]{width:100%!important}td[class="buttonContent"]{padding:0!important}td[class="buttonContent"] a{padding:15px!important}}</style>\n';
        code += '<!--[if mso 12]>\n';
        code += '<style type="text/css">.flexibleContainer{display:block!important;width:100%!important}</style>\n';
        code += '<![endif]-->\n';
        code += '<!--[if mso 14]>\n';
        code += '<style type="text/css">.flexibleContainer{display:block!important;width:100%!important}</style>\n';
        code += '<![endif]-->\n';
        code += '</head>\n';
        code += '<body bgcolor="#E1E1E1" leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">\n';
        code += '<center style="background-color:#E1E1E1">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="table-layout:fixed;max-width:100%!important;width:100%!important;min-width:100%!important">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" id="bodyCell">\n';
        code += '<table bgcolor="#E1E1E1" border="0" cellpadding="0" cellspacing="0" width="500" id="emailHeader">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="10" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="middle" id="invisibleIntroduction" class="flexibleContainerBox" style="display:none!important;mso-hide:all">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="middle" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '<table bgcolor="#FFFFFF" border="0" cellpadding="0" cellspacing="0" width="500" id="emailBody">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="background-color:#2196f3">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="color:#FFFFFF" bgcolor="#3498db">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" class="textContent">\n';
        code += '<h1 style="color:#FFFFFF;line-height:100%;font-family:Helvetica,Arial,sans-serif;font-size:35px;font-weight:normal;margin-bottom:5px;text-align:center">LAVISA</h1>\n';
        code += '<h2 style="text-align:center;font-weight:normal;font-family:Helvetica,Arial,sans-serif;font-size:23px;margin-bottom:10px;color:#e3f2fd;line-height:135%">Fell Free to Save your money</h2>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#F8F8F8">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td valign="top" class="textContent">\n';
        code += '<h3 mc:edit="header" style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:center">Confirmation</h3>\n';
        code += '<div mc:edit="body" style="text-align:center;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">This is detail of your transaction.</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<img src="http://saas.lavisa.id/assets/img/send.jpg" width="210" class="flexibleImage" style="max-width:100%" alt="Text" title="Text" />\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Sender</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">\n';
        code += '<p>Name : ' + data.senderName + '</p>\n';
        code += '<p>Address : ' + data.senderAddress + '</p>\n';
        code += '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Receiver</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">\n';
        code += '<p>Name : ' + data.receiverName + '</p>\n';
        code += '<p>Bank : ' + data.receiverBankName + '</p>\n';
        code += '<p>Account Number : ' + data.receiverBankAccountNumber + '</p>\n';
        code += '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<img src="http://saas.lavisa.id/assets/img/receive.jpg" width="210" class="flexibleImage" style="max-width:100%" alt="Text" title="Text" />\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox" style="background-color:#5F5F5F">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#FFFFFF;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">You will get</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#FFFFFF;line-height:135%"> ('+data.originalCurrency+') ' + data.originalAmount + '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox" style="background-color:#27ae60">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="30" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#FFFFFF;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Already Converted</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#FFFFFF;line-height:135%"> X ' + data.exchange + ' = ('+data.destinationCurrency+') ' + data.destinationAmount + '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td valign="top" class="textContent">\n';
        code += '<div style="text-align:center;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;margin-top:3px;color:#5F5F5F;line-height:135%"></div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</center>\n';
        code += '</body>\n';
        code += '</html>';

        return code;
    },

    /**
    * An email template (PLAIN) for transfer.
    *
    * @param    JSON     data
    * @return   string
    */
    transferPlain: function(data)
    {
        return 'Neest: Fell Free to Save your money.\n\n\n' +
            'Confirmation\nYou will transaction with this detail.\n\n\n' +
            'Sender:\nName: ' + data.senderName + '\nAccount Number: ' + data.senderBankAccountNumber +
            '\n\n' + 'Receiver:\nName: ' + data.receiverName + '\nAccount Number: ' + data.receiverBankAccountNumber +
            '\n\n' + 'You will get: ' + data.originalAmount + ' $\n' + 'Already Converted: X '
            + data.exchange + ' = Rp.' + data.destinationAmount + '';
    },

    /**
    * An email template (HTML) for cash.
    *
    * @param    JSON     data
    * @return   string
    */
    cashHTML: function(data)
    {
        var code = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n';
        code += '<html xmlns="http://www.w3.org/1999/xhtml">\n';
        code += '<head>\n';
        code += '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n';
        code += '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
        code += '<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n';
        code += '<meta name="format-detection" content="telephone=no" />\n';
        code += '<title>E-Mail</title>\n';
        code += '<style type="text/css">html{background-color:#e1e1e1;margin:0;padding:0}body,#bodyTable,#bodyCell,#bodyCell{height:100%!important;margin:0;padding:0;width:100%!important;font-family:Helvetica,Arial,"Lucida Grande",sans-serif}table{border-collapse:collapse}table[id=bodyTable]{width:100%!important;margin:auto;max-width:500px!important;color:#7a7a7a;font-weight:normal}img,a img{border:0;outline:0;text-decoration:none;height:auto;line-height:100%}a{text-decoration:none!important;border-bottom:1px solid}h1,h2,h3,h4,h5,h6{color:#5f5f5f;font-weight:normal;font-family:Helvetica;font-size:20px;line-height:125%;text-align:Left;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:10px;margin-left:0;padding-top:0;padding-bottom:0;padding-left:0;padding-right:0}.ReadMsgBody{width:100%}.ExternalClass{width:100%}.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{line-height:100%}table,td{mso-table-lspace:0;mso-table-rspace:0}#outlook a{padding:0}img{-ms-interpolation-mode:bicubic;display:block;outline:0;text-decoration:none}body,table,td,p,a,li,blockquote{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;font-weight:normal!important}.ExternalClass td[class="ecxflexibleContainerBox"] h3{padding-top:10px!important}h1{display:block;font-size:26px;font-style:normal;font-weight:normal;line-height:100%}h2{display:block;font-size:20px;font-style:normal;font-weight:normal;line-height:120%}h3{display:block;font-size:17px;font-style:normal;font-weight:normal;line-height:110%}h4{display:block;font-size:18px;font-style:italic;font-weight:normal;line-height:100%}.flexibleImage{height:auto}.linkRemoveBorder{border-bottom:0!important}table[class=flexibleContainerCellDivider]{padding-bottom:0!important;padding-top:0!important}body,#bodyTable{background-color:#e1e1e1}#emailHeader{background-color:#e1e1e1}#emailBody{background-color:#fff}#emailFooter{background-color:#e1e1e1}.nestedContainer{background-color:#f8f8f8;border:1px solid #ccc}.emailButton{background-color:#205478;border-collapse:separate}.buttonContent{color:#fff;font-family:Helvetica;font-size:18px;font-weight:bold;line-height:100%;padding:15px;text-align:center}.buttonContent a{color:#fff;display:block;text-decoration:none!important;border:0!important}.emailCalendar{background-color:#fff;border:1px solid #ccc}.emailCalendarMonth{background-color:#205478;color:#fff;font-family:Helvetica,Arial,sans-serif;font-size:16px;font-weight:bold;padding-top:10px;padding-bottom:10px;text-align:center}.emailCalendarDay{color:#205478;font-family:Helvetica,Arial,sans-serif;font-size:60px;font-weight:bold;line-height:100%;padding-top:20px;padding-bottom:20px;text-align:center}.imageContentText{margin-top:10px;line-height:0}.imageContentText a{line-height:0}#invisibleIntroduction{display:none!important}span[class=ios-color-hack] a{color:#275100!important;text-decoration:none!important}span[class=ios-color-hack2] a{color:#205478!important;text-decoration:none!important}span[class=ios-color-hack3] a{color:#8B8B8B!important;text-decoration:none!important}.a[href^="tel"],a[href^="sms"]{text-decoration:none!important;color:#606060!important;pointer-events:none!important;cursor:default!important}.mobile_link a[href^="tel"],.mobile_link a[href^="sms"]{text-decoration:none!important;color:#606060!important;pointer-events:auto!important;cursor:default!important}@media only screen and (max-width:480px){body{width:100%!important;min-width:100%!important}table[id="emailHeader"],table[id="emailBody"],table[id="emailFooter"],table[class="flexibleContainer"],td[class="flexibleContainerCell"]{width:100%!important}td[class="flexibleContainerBox"],td[class="flexibleContainerBox"] table{display:block;width:100%;text-align:left}td[class="imageContent"] img{height:auto!important;width:100%!important;max-width:100%!important}img[class="flexibleImage"]{height:auto!important;width:100%!important;max-width:100%!important}img[class="flexibleImageSmall"]{height:auto!important;width:auto!important}table[class="flexibleContainerBoxNext"]{padding-top:10px!important}table[class="emailButton"]{width:100%!important}td[class="buttonContent"]{padding:0!important}td[class="buttonContent"] a{padding:15px!important}}</style>\n';
        code += '<!--[if mso 12]>\n';
        code += '<style type="text/css">.flexibleContainer{display:block!important;width:100%!important}</style>\n';
        code += '<![endif]-->\n';
        code += '<!--[if mso 14]>\n';
        code += '<style type="text/css">.flexibleContainer{display:block!important;width:100%!important}</style>\n';
        code += '<![endif]-->\n';
        code += '</head>\n';
        code += '<body bgcolor="#E1E1E1" leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">\n';
        code += '<center style="background-color:#E1E1E1">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="table-layout:fixed;max-width:100%!important;width:100%!important;min-width:100%!important">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" id="bodyCell">\n';
        code += '<table bgcolor="#E1E1E1" border="0" cellpadding="0" cellspacing="0" width="500" id="emailHeader">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="10" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="middle" id="invisibleIntroduction" class="flexibleContainerBox" style="display:none!important;mso-hide:all">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="middle" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '<table bgcolor="#FFFFFF" border="0" cellpadding="0" cellspacing="0" width="500" id="emailBody">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="background-color:#2196f3">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="color:#FFFFFF" bgcolor="#3498db">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" class="textContent">\n';
        code += '<h1 style="color:#FFFFFF;line-height:100%;font-family:Helvetica,Arial,sans-serif;font-size:35px;font-weight:normal;margin-bottom:5px;text-align:center">Lavisa</h1>\n';
        code += '<h2 style="text-align:center;font-weight:normal;font-family:Helvetica,Arial,sans-serif;font-size:23px;margin-bottom:10px;color:#e3f2fd;line-height:135%">Fell Free to Save your money</h2>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="#F8F8F8">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td valign="top" class="textContent">\n';
        code += '<h3 mc:edit="header" style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:center">Confirmation</h3>\n';
        code += '<div mc:edit="body" style="text-align:center;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">This is detail of your transaction.</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<img src="http://saas.lavisa.id/assets/img/send.jpg" width="210" class="flexibleImage" style="max-width:100%" alt="Text" title="Text" />\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Sender</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">\n';
        code += '<p>Name : ' + data.senderName + '</p>\n';
        code += '<p>Phone : ' + data.senderPhone + '</p>\n';
        code += '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#5F5F5F;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Receiver</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#5F5F5F;line-height:135%">\n';
        code += '<p>Name : ' + data.receiverName + '</p>\n';
        code += '<p>Phone : ' + data.receiverPhone + '</p>\n';
        code += '<p>Pin : ' + data.pinBranch.pin + '</p>\n';
        code += '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="0" cellspacing="0" width="210" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<img src="http://saas.lavisa.id/assets/img/receive.jpg" width="210" class="flexibleImage" style="max-width:100%" alt="Text" title="Text" />\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table class="flexibleContainerCellDivider" border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="padding-top:0px;padding-bottom:0px">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" style="border-top:1px solid #c8c8c8"></td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table align="left" border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="left" valign="top" class="flexibleContainerBox" style="background-color:#5F5F5F">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#FFFFFF;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">You will get</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#FFFFFF;line-height:135%"> ('+data.originalCurrency+') ' + data.originalAmount + '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '<td align="right" valign="top" class="flexibleContainerBox" style="background-color:#27ae60">\n';
        code += '<table class="flexibleContainerBoxNext" border="0" cellpadding="30" cellspacing="0" width="100%" style="max-width:100%">\n';
        code += '<tr>\n';
        code += '<td align="left" class="textContent">\n';
        code += '<h3 style="color:#FFFFFF;line-height:125%;font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:normal;margin-top:0;margin-bottom:3px;text-align:left">Already Converted</h3>\n';
        code += '<div style="text-align:left;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;color:#FFFFFF;line-height:135%"> X ' + data.exchange + ' = ('+data.destinationCurrency+') ' + data.destinationAmount + '</div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="500" class="flexibleContainer">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top" width="500" class="flexibleContainerCell">\n';
        code += '<table border="0" cellpadding="30" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td align="center" valign="top">\n';
        code += '<table border="0" cellpadding="0" cellspacing="0" width="100%">\n';
        code += '<tr>\n';
        code += '<td valign="top" class="textContent">\n';
        code += '<div style="text-align:center;font-family:Helvetica,Arial,sans-serif;font-size:15px;margin-bottom:0;margin-top:3px;color:#5F5F5F;line-height:135%"></div>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</td>\n';
        code += '</tr>\n';
        code += '</table>\n';
        code += '</center>\n';
        code += '</body>\n';
        code += '</html>';

        return code;
    },

    /**
    * An email template (PLAIN) for cash.
    *
    * @param    JSON     data
    * @return   string
    */
    cashPlain: function(data)
    {
        return 'Neest: Fell Free to Save your money.\n\n\n' +
            'Confirmation\nYou will transaction with this detail.\n\n\n' +
            'Sender:\nName: ' + data.senderName + '\nPhone: ' + data.senderPhone +
            '\n\n' + 'Receiver:\nName: ' + data.receiverName + '\nPhone: ' + data.receiverPhone +
            '\n\n' + 'You will get: ' + data.originalAmount + ' $\n' + 'Already Converted: X '
            + data.exchange + ' = Rp.' + data.destinationAmount + '';
    }
};
